cart/urls.py
from django.urls import path
from . import views 

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),

    path('checkout/', views.checkout, name='checkout'),

]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('store/', include('store.urls')),
    path('cart/', include('cart.urls')),
    path('accounts/', include('accounts.urls')),
    path('adminpanel/', include('adminpanel.urls')),
    path('orders/', include('orders.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/models.py
from email.policy import default
from tkinter import CASCADE
from django.db import models
from category.models import Category 
from django.urls import reverse
from accounts.models import Account
from django.db.models import Avg, Count



class Product(models.Model):
    product_name = models.CharField(max_length = 200, unique=True)
    slug         = models.SlugField(max_length = 200, unique=True)
    description  = models.TextField(max_length=500, blank = True)
    price        = models.IntegerField()
    image        = models.ImageField(upload_to='photos/products')
    stock        = models.IntegerField()
    is_available = models.BooleanField(default=True)
    category     = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)


    def get_url(self):
        return reverse('product_detail', args=[self.category.slug, self.slug])

    def __str__(self):
        return self.product_name

    def averageReview(self):
        reviews = ReviewRating.objects.filter(product = self, status=True).aggregate(average=Avg('rating'))
        avg = 0
        if reviews['average'] is not None:
            avg = float(reviews['average'])
        return avg

    def countReview(self):
        reviews = ReviewRating.objects.filter(product = self, status=True).aggregate(count=Count('id'))
        count = 0
        if reviews['count'] is not None:
            count = int(reviews['count'])
        return count


class VariationManager(models.Manager):
    def materials(self):
        return super(VariationManager, self).filter(variation_category = 'material', is_active=True)


variation_category_choice = (
    ('material', 'material'),
)


class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(max_length=100, choices=variation_category_choice)
    variation_value = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now=True)

    object = VariationManager()
 
    def __str__(self):
        return self.variation_value


 
class ReviewRating(models.Model):
    product    = models.ForeignKey(Product, on_delete=models.CASCADE)
    user       = models.ForeignKey(Account, on_delete=models.CASCADE)
    subject    = models.CharField(max_length=100, blank=True)
    review     = models.TextField(max_length=500, blank=True)
    rating     = models.FloatField()
    ip         = models.CharField(max_length=20, blank=True)
    status     = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject

templates/manager/add_variation.html
{% extends 'base.html' %} {% block content %}
<section class="section-content padding-y bg">
  <div class="container">
    <div class="row d-flex justify-content-center">
      <div class="col-8">
        <h1 class="text-center h2 mb-4">Add Variation</h1>
        <form action="{% url 'add_variation' %}" method="POST">
          {% csrf_token %}
          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="id_name">Product Name</label>
              {{ form.product }}
            </div>
            <div class="form-group col-md-6">
              <label for="product_slug">Variation Category</label>
              {{ form.variation_category }}
            </div>
          </div>
          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="product_price">Variation Value</label>
              {{ form.variation_value }}
            </div>
            <div class="form-group col-md-6">
              <label for="id_is_available">Active</label>
              {{ form.is_active }}
            </div>
          <div class="text-center">
            <button type="submit" class="btn btn-dark">Save</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

templates/manager/admin_change_password.html
{% extends 'base.html' %} {% block content %}
<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y bg">
  <div class="container">
    <h1 class="text-center h2 mb-4">Change Password</h1>
    <div class="row">
      {% include 'includes/admindashboardsidebar.html' %}
      <main class="col-md-9">
        {% if messages %} {% for message in messages %}
        {% if message.tags == 'success' %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% elif message.tags == 'error' %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% else %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endif %}
        {% endfor %} {% endif %}
        <form action='{% url 'admin_change_password' %}' method='POST'>
          {% csrf_token %}
          <div class="form-group">
            <label for="current_password">Current Password</label>
            <input type="password" class="form-control" id="current_password" name="current_password" placeholder="Enter current password" />
          </div>
          <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="Enter new password" />
          </div>
          <div class="form-group">
            <label for="confirm_password">Retype Password</label>
            <input type="password" class="form-control" id="confirm_password" name="confirm_password" placeholder="Enter confirm password" />
          </div>
          <button type="submit" class="btn btn-dark">Submit</button>
        </form>
      </main>
    </div>
    <!-- row.// -->
  </div>
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock content %}

templates/manager/admin_orders.html
{% extends 'base.html' %} {% block content %}
<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content mt-3 bg">
  <div class="container">
    <h1 class="text-center h2 mb-4">My Orders</h1>
    <div class="d-flex mb-3 justify-content-end">
      <form action="{% url 'admin_orders' %}" class="search" method="POST">
        {% csrf_token %} 
        <div class="input-group w-100">
          <input type="text" class="form-control" style="width: 60%" placeholder="Search" name="keyword" />

          <div class="input-group-append">
            <button class="btn btn-dark" type="submit">
              <i class="fa fa-search"></i>
            </button>
          </div>
        </div>
      </form>
    </div>
    <div class="row">
      {% include 'includes/admindashboardsidebar.html' %}
      <main class="col-md-9">
        <table class="table table-borderless">
          <thead>
            <tr>
              <th scope="col">Order #</th>
              <th scope="col">User</th>
              <th scope="col">Billing Name</th>
              <th scope="col">Phone Number</th>
              <th scope="col">Order Total</th>
              <th scope="col">Order Status</th>
              <th scope="col">Order Cancel</th>
            </tr>
          </thead>
          <tbody>
            {% for order in orders %}
            <tr>
              <th scope="row"><a href="{% url 'order_detail' order.order_number %}">{{ order.order_number }}</a></th>
              <td>{{ order.user }}</td>
              <td>{{ order.full_name }}</td>
              <td>{{ order.phone }}</td>
              <td>₹ {{ order.order_total }}</td>
              <td>
                {% if order.status == 'Cancelled' %}
                <span class="text-danger font-weight-bold">{{ order.status }}</span>
                {% elif order.status == 'Completed' %}
                <span class="text-success font-weight-bold">{{ order.status }}</span>
                {% elif order.status == 'Pending' %}
                <span class="text-muted font-weight-bold">{{ order.status }}</span>
                {% else %} <span class="text-info font-weight-bold">{{ order.status }}</span>
                {% endif %}
              </td>
              <td>
                {% if order.status == 'Accepted' %}
                <a href="{% url 'admin_cancel_order' order.order_number %}" class="btn btn-danger btn-sm">Cancel</a>
                {% elif order.status == 'Pending' %}
                <a href="{% url 'admin_cancel_order' order.order_number %}" class="btn btn-danger btn-sm">Cancel</a>
                {% endif %}
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </main>
    </div>
    <!-- row.// -->
  </div>
  <div class="container">
    <div class="row">
      <aside class="col-md-3"></aside>
      <main class="col-md-9">
        <nav class="mt-4" aria-label="Page navigation sample">
          {% if orders.has_other_pages %}
          <ul class="pagination">
            {% if orders.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ orders.previous_page_number }}">Previous</a></li>
            {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
            {% endif %} {% for page_number in orders.paginator.page_range %} {% if orders.number == page_number %}
            <li class="page-item active"><a class="page-link" href="#">{{ page_number }}</a></li>
            {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a></li>
            {% endif %} {% endfor %} {% if orders.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ orders.next_page_number }}">Next</a></li>
            {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
            {% endif %}
          </ul>
          {% endif %}
        </nav>
      </main>
    </div>
  </div>
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock content %}

templates/manager/category_add.html
{% extends 'base.html' %} {% block content %}
<section class="section-content padding-y bg">
  <div class="container">
    <div class="row d-flex justify-content-center">
      <div class="col-12">
        <h1 class="text-center h2 mb-4">Add Category</h1>
        <form action="{% url 'add_category' %}" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="id_name">Category Name</label>
              {{ form.category_name }}
            </div> 
            <div class="form-group col-md-6">
              <label for="category_slug">Category Slug</label>
              {{ form.slug }}
              
            </div>
          </div>
          <div class="text-center">
            <button type="submit" class="btn btn-dark">Save <i class="fa fa-bookmark" aria-hidden="true"></i></button>
          </div>
        </form> 
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/manager/category_management.html
{% extends 'base.html' %} {% block content %}
<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content mt-3 bg">
  <div class="container">
    <h1 class="text-center h2 mb-4">Manage Categories</h1>
    <div class="d-flex mb-3 justify-content-end">
      <form action="{% url 'manage_category' %}" class="search" method="POST">
        {% csrf_token %} 
        <div class="input-group w-100">
          <input type="text" class="form-control" style="width: 60%" placeholder="Search" name="keyword" />

          <div class="input-group-append">
            <button class="btn btn-dark" type="submit">
              <i class="fa fa-search"></i>
            </button>
          </div>
        </div>
      </form>
    </div>
    <div class="row">
      {% include 'includes/admindashboardsidebar.html' %}
      <main class="col-md-9">
        <div class="d-flex justify-content-end">
          <a href="{% url 'add_category' %}" class="btn btn-info mr-md-0">Add <i class="fa fa-plus-circle" aria-hidden="true"></i></a>
        </div>
        <table class="table table-borderless">
          <thead>
            <tr>
              <th scope="col">ID</th>
              <th scope="col">Category Name</th>
              <th scope="col">Category Slug</th>
              <th scope="col">Delete</th>
            </tr>
          </thead>
          <tbody>
            {% for category in categories %}
            <tr>
              <th scope="row">{{ category.id }}</th>
              <td>{{ category.category_name }}</td>
              <td>{{ category.slug }}</td>
              <td><a href="{% url 'delete_category' category.id %}" class="btn btn-sm btn-danger">Delete <i class="fa fa-trash" aria-hidden="true"></i></a></td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        <!-- order-group.// -->
        <div class="container">
          <div class="row">
            <aside class="col-md-3"></aside>
            <main class="col-md-9">
              <nav class="mt-4" aria-label="Page navigation sample">
                {% if categories.has_other_pages %}
                <ul class="pagination">
                  {% if categories.has_previous %}
                  <li class="page-item"><a class="page-link" href="?page={{ categories.previous_page_number }}">Previous</a></li>
                  {% else %}
                  <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
                  {% endif %} {% for page_number in categories.paginator.page_range %} {% if categories.number == page_number %}
                  <li class="page-item active"><a class="page-link" href="#">{{ page_number }}</a></li>
                  {% else %}
                  <li class="page-item"><a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a></li>
                  {% endif %} {% endfor %} {% if categories.has_next %}
                  <li class="page-item"><a class="page-link" href="?page={{ categories.next_page_number }}">Next</a></li>
                  {% else %}
                  <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
                  {% endif %}
                </ul>
                {% endif %}
              </nav>
            </main>
          </div>
      </main> 
    </div>
    <!-- row.// -->
  </div>

  </div>
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock content %}

templates/manager/edit_product.html
{% extends 'base.html' %} {% block content %}
<section class="section-content padding-y bg">
  <div class="container">
    <div class="row d-flex justify-content-center">
      <div class="col-8">
        <h1 class="text-center h2 mb-4">Edit Product</h1>
        <form action="{% url 'edit_product' product.id %}" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="id_name">Product Name</label>
              {{ form.product_name }}
            </div>
            <div class="form-group col-md-6">
              <label for="product_slug">Product Slug</label>
              {{ form.slug }}
              <small id="product_slug" class="form-text text-muted">Format :- name: ATX Jeans, slug: atx-jeans</small>
            </div>
          </div>
          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="product_price">Product Price</label>
              {{ form.price }}
            </div>
            <div class="form-group col-md-6">
              <label for="product_image">Product Image</label>
              {{ form.image }}
            </div>
            <div class="form-group col-md-6">
              <label for="product_stock">Product Stock</label>
              {{ form.stock }}
            </div>
            <div class="form-group col-md-6">
              <label for="product_category">Category</label>
              {{ form.category }}
            </div>
            <div class="form-group col-md-6">
              <label for="id_is_available">Available</label>
              {{ form.is_available }}
            </div>
          </div>

          <div class="form-group">
            <label for="product_description">Product Description</label>
            {{ form.description }}
          </div>
          <div class="text-center">
            <button type="submit" class="btn btn-dark">Save  <i class="bi bi-sd-card-fill"></i></button>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

templates/manager/manager_dashboard.html
{% extends 'base.html' %}

{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
   
<section class="section-conten mt-3 bg">
    <div class="container">
      <h1 class="text-center h2 mb-4">Admin Dashboard</h1>
       <div class="row">
        
        {% include 'includes/admindashboardsidebar.html' %}
       <main class="col-md-9">
          <div class="row">
            <div class="col-sm-6 text-center mb-2 ">
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title">Total Users </h5>
                  <p class="card-title h4 mb-3">{{ user_count }}</p>
                  <a href="{% url 'manage_user' %}" class="btn btn-outline-dark">View Users</a>
                </div>
              </div>
            </div>
            <div class="col-sm-6 text-center mb-2">
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title">Total Products</h5>
                  <p class="card-title h4 mb-3">{{ product_count }}</p>
                  <a href="{% url 'manage_product' %}" class="btn btn-outline-dark">View Products</a>
                </div>
              </div>
            </div>
            <div class="col-sm-6 text-center mb-2">
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title">Product Category</h5>
                  <p class="card-title h4 mb-3">{{ category_count }}</p>
                  <a href="{% url 'manage_category' %}" class="btn btn-outline-dark">View Categories</a>
                </div>
              </div>
            </div>
            <div class="col-sm-6 text-center mb-2">
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title">Total Orders</h5>
                  <p class="card-title h4 mb-3">{{ order_count }}</p>
                  <a href="{% url 'manage_order' %}" class="btn btn-outline-dark">View Orders</a>
                </div>
              </div>
            </div>  
            {% comment %} <div class="col text-center mb-2">
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title">Total Sales</h5>
                  <p class="card-title h4 mb-3">₹ {{ total_sales }}</p>
                </div>
              </div>
            </div> {% endcomment %}
          </div>
          <div class="w-75"> 
            <canvas id="myChart" width="300" height="300"></canvas>
          </div>
    
          <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    
          <script>
            const ctx = document.getElementById('myChart');
    
            new Chart(ctx, {
              type: 'doughnut',
              data: {
                labels: ['Order', 'Product', 'User', 'Category'],
                datasets: [{
                  label: '',
                  data: ['{{order_count}}', '{{product_count}}', '{{user_count}}', '{{category_count}}'],
                  borderWidth: 1
                }]
              },
              options: {
                scales: {
                  y: {
                    beginAtZero: true
                  }
                }
              }
            });
          </script>
  
          <!-- order-group.// -->
        </main>
      </div>
      <!-- row.// -->
    </div> 
  </section>
  
 
  <!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}

templates/manager/manager_signin.html
{% extends 'base.html' %}

{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height: 84vh">
    <!-- ============================ COMPONENT LOGIN   ================================= -->
    <div class="card mx-auto" style="max-width: 380px; margin-top: 100px">
      <div class="card-body">
        <h4 class="card-title mb-4 text-center">Admin Panel</h4>
  
        {% comment %} Error messages {% endcomment %} {% if messages %} {% for message in messages %} {% if message.tags == 'error' %}
        <p id="messages" style="font-weight: 600; color: red" class="text-center">{{ message }}</p>
  
        {% elif message.tags == 'warning' %}
        <p id="messages" style="font-weight: 600; color: #ffcc00" class="text-center">{{ message }}</p>
  
        {% elif message.tags == 'success' %}
        <p id="messages" style="font-weight: 600; color: green" class="text-center">{{ message }}</p>
  
        {% endif %} {% endfor %} {% endif %}
  
        <form method="POST" action="{% url 'manager_login' %}">
        {% csrf_token %}
          <div class="form-group">
            <input type="email" class="form-control" placeholder="Email Address" name="email" />
          </div>
          <!-- form-group// -->
          <div class="form-group">
            <input type="password" class="form-control" placeholder="Password" name="password" />
          </div>
          <!-- form-group// -->
   
          <div class="form-group">
            <button type="submit" class="btn btn-dark btn-block">Login</button>
          </div>
          <!-- form-group// -->
        </form>
      </div>
      <!-- card-body.// -->
    </div>
    <!-- card .// -->
    <br /><br />
    <!-- ============================ COMPONENT LOGIN  END.// ================================= -->
  </section>
  <!-- ========================= SECTION CONTENT END// ========================= -->
  


{% endblock content %}

templates/manager/order_management.html
{% extends 'base.html' %}

{% block content %}
<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content mt-3 bg">
  <div class="container">
    <h1 class="text-center h2 mb-4">Manage Orders</h1>
    <div class="d-flex mb-3 justify-content-end">
      <form action="{% url 'manage_order' %}" class="search" method="POST">
        {% csrf_token %} 
        <div class="input-group w-100">
          <input type="text" class="form-control" style="width: 60%" placeholder="Search" name="keyword" />

          <div class="input-group-append">
            <button class="btn btn-dark" type="submit">
              <i class="fa fa-search"></i>
            </button>
          </div>
        </div>
      </form>
    </div>
    <div class="row">
      {% include 'includes/admindashboardsidebar.html' %}
      <main class="col-md-9">
        <table class="table table-borderless">
          <thead>
            <tr>
              <th scope="col">Order Number</th>
              <th scope="col">User</th>
              <th scope="col">Billing Name</th>
              <th scope="col">Total</th>
              <th scope="col">Status</th>
              <th scope="col"></th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
            {% for order in orders %}
            <tr>
              <th scope="row"><a href="{% url 'order_detail' order.order_number %}">{{ order.order_number }}</a></th>
              <td>{{ order.user }}</td>
              <td>{{ order.full_name }}</td>
              <td>{{ order.order_total }}</td>
              <td>
                {% if order.status == 'Order Cancelled' %}
                <span class="text-danger font-weight-bold">{{ order.status }}</span>
                {% elif order.status == 'Delivered Successfully' %}
                <span class="text-success font-weight-bold">{{ order.status }}</span>
                {% elif order.status == 'Pending' %}
                <span class="text-muted font-weight-bold">{{ order.status }}</span>
                {% else %} <span class="text-info font-weight-bold">{{ order.status }}</span>
                {% endif %}
              </td>
              <td>
                {% if order.status == 'Pending' %}
                <a href="{% url 'accept_order' order.order_number %}" class="btn btn-sm btn-info">Accept</a>
                {% elif order.status == 'Order Accepted' %}
                <a href="{% url 'complete_order' order.order_number %}" class="btn btn-sm btn-success">Complete</a>
                {% endif %}
              </td>
              <td>
                {% if order.status == 'Pending' or order.status == 'Order Accepted' %}
                <a href="{% url 'admin_cancel_order' order.order_number %}" class="btn btn-sm btn-danger">Cancel</a>
                {% endif %}
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        <!-- order-group.// -->
      </main>
    </div>
    <!-- row.// -->
  </div>

  <div class="container">
    <div class="row">
      <aside class="col-md-3"></aside>
      <main class="col-md-9">
        <nav class="mt-4" aria-label="Page navigation sample">
          {% if orders.has_other_pages %}
          <ul class="pagination">
            {% if orders.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ orders.previous_page_number }}">Previous</a></li>
            {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
            {% endif %} {% for page_number in orders.paginator.page_range %} {% if orders.number == page_number %}
            <li class="page-item active"><a class="page-link" href="#">{{ page_number }}</a></li>
            {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a></li>
            {% endif %} {% endfor %} {% if orders.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ orders.next_page_number }}">Next</a></li>
            {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
            {% endif %}
          </ul>
          {% endif %}
        </nav>
      </main>
    </div>
  </div>
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock content %}

templates/manager/update_variation.html
{% extends 'base.html' %} {% block content %}
<section class="section-content padding-y bg">
  <div class="container">
    <div class="row d-flex justify-content-center">
      <div class="col-8">
        <h1 class="text-center h2 mb-4">Edit Variation</h1>
        <form action="{% url 'update_variation' variation.id %}" method="POST">
          {% csrf_token %}
          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="id_name">Product Name</label>
              {{ form.product }}
            </div>
            <div class="form-group col-md-6">
              <label for="product_slug">Variation Category</label>
              {{ form.variation_category }}
            </div>
          </div>
          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="product_price">Variation Value</label>
              {{ form.variation_value }}
            </div>
            <div class="form-group col-md-6">
              <label for="id_is_available">Active</label>
              {{ form.is_active }}
            </div>
          <div class="text-center">
            <button type="submit" class="btn btn-dark">Save</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>

{% endblock content %}